import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

	// But you can create a sidebar manually
	tutorialSidebar: [
		"intro",
		{
			type: "category",
			label: "Basics",
			items: [
				"core-module/installation",
				"core-module/controllers",
				"core-module/error-validate",
				"core-module/parameter-decorators",
			],
		},
		{
			type: "category",
			label: "Middlewares",
			items: [
				"middlewares/use",
				"middlewares/catch",
				"middlewares/intercept",
				"middlewares/pipe",
				"middlewares/sanitize",
				"middlewares/cors",
				"middlewares/guard",
			],
		},
		{
			type: "category",
			label: "Http",
			items: [
				"http-module/server",
				"http-module/websockets",
				"http-module/server-sent-events",
				"http-module/graph-ql",
				"http-module/plugins",
			],
		},
		{
			type: "category",
			label: "AWS",
			items: ["aws/lambda-integration", "aws/plugins"],
		},
		{
			type: "category",
			label: "GRPC",
			items: ["grpc/module", "grpc/usage", "grpc/api", "grpc/examples"],
		},
	],
};

export default sidebars;
